### PR TITLE
Fix for label templates sometimes not resolving: https://github.com/k…

### PR DESCRIPTION
**Pull request by Nicholas-Westby**
…giszewski/Archetype/issues/432

### CODE REVIEW

**Comment by kgiszewski** [comment]
Ill look at this tomorrow. I have some test cases hanging around still. My last refactor effort is to blame. Sorry sir.

**Comment by Nicholas-Westby** [comment]
No worries. You do awesome work :-)

**Comment by kgiszewski** [comment]
Seems to work fine with my test cases. Now when to release this...

**Comment by Nicholas-Westby** [comment]
My vote's today :-)

**Comment by kgiszewski** [comment]
Ok, lemme try to get it out.

**Pull request merged**
