### PR TITLE
Feature/422 label template enhancements

### PR DESCRIPTION
**Pull request by Nicholas-Westby**
Allow label template functions to return promises and functions that can be invoked with injected dependencies.

### CODE REVIEW

**Comment by kgiszewski** [comment]
This is looking good @Nicholas-Westby :+1:

I need to put it thru the wringer and we'll get this guy merged in.

I would like a promise (or 2) example from you to verify your intent and functionality.

**Comment by kgiszewski** [comment]
@kjac Another set of eyes would be helpful :)

**Comment by Nicholas-Westby** [comment]
Just made one more change (to allow for the functions to return things like numbers).

Also, did you see this comment?: https://github.com/kgiszewski/Archetype/issues/422#issuecomment-327369244

It has some examples, including one promise example, which I'll paste again here for quick reference:

```javascript
// Returns a function to be invoked with dependency injection,
// which in turn returns a promise to be resolved to a string value.
function testPromise(value) {
    return function ($timeout) {
        return $timeout(function () {
            return "As Promised: " + value;
        }, 1000);
    }
}
```

The `$timeout` function returns a promise. Perhaps you are wanting an example that returns a promise before it returns a function? If so, here is one:

```javascript
// Returns a promise to be resolved to a string value.
window.testPromise2 = function(value) {
    return $timeout(function () {
        return "As Promised: " + value;
    }, 1000);
};
```

The trick is, that won't work unless this function exists inside of another function that happens to have a `$timeout` variable. For example, if you wanted to add this directly to Archetype, you could do so in `archetypeLabelService.js`:

```javascript
angular.module('umbraco.services').factory('archetypeLabelService', function (
    archetypeCacheService, $q, $injector,
    // Note I added the $timeout dependency.
    $timeout) {

    // Returns a promise to be resolved to a string value.
    window.testPromise2 = function(value) {
        return $timeout(function () {
            return "As Promised: " + value;
        }, 1000);
    };
```

I'll see if I can work on an `$http` example to actually do something useful.

**Comment by Nicholas-Westby** [comment]
OK, I just put together a... useful... example:

```javascript
angular.module('umbraco.services').factory('archetypeLabelService', function (
    archetypeCacheService, $q, $injector,
    // Note I added the userService dependency.
    userService) {

    // Returns a promise to be resolved to a string value.
    window.userFirstName = function() {
        return userService.getCurrentUser().then(function (user) {
            return user.name.split(" ")[0];
        });
    };
```

You can then use a label template like this:

```
{{userFirstName()}} Likes {{petName}}
```

When might render to a label like this:

```
Kevin Likes Toytles
```

So [useful](https://www.youtube.com/watch?v=CMNry4PE93Y).

Again, this could be rewritten like so (thanks to the new dependency injection capability):

```javascript
// Returns a function that returns a promise to be resolved to a string value.
function userFirstName() {
    return function (userService) {
        return userService.getCurrentUser().then(function (user) {
            return user.name.split(" ")[0];
        });
    };
};
```

**Comment by kgiszewski** [comment]
Awesome, I hope to get to test it out tomorrow!

**Comment by kjac** [comment]
The code looks good to me. I don't have time to test atm, but I'm sure you guys are more than capable 😄

**Comment by kgiszewski** [comment]
@kjac no worries, I'm planning on checking out the code and testing locally today.

**Comment by kgiszewski** [comment]
Hey bud, testing this out I stumbled on a bug:

image

**Comment by kgiszewski** [comment]
The Archetype fieldset is throw exceptions. This particular one is a simple headline + image list:

image

The template is blank and should by default return the name of the fieldset.

**Comment by kgiszewski** [comment]
I'm gonna keep testing, so for now I'll put in a template into the offending fieldset configs.

**Comment by kgiszewski** [comment]
image

Everything else is testing out good too except this form doesn't make sense to me (below):
```angular.module('umbraco.services').factory('archetypeLabelService', function (
    archetypeCacheService, $q, $injector,
    // Note I added the userService dependency.
    userService) {

    // Returns a promise to be resolved to a string value.
    window.userFirstName = function() {
        return userService.getCurrentUser().then(function (user) {
            return user.name.split(" ")[0];
        });
    };```

**Comment by kgiszewski** [comment]
@Nicholas-Westby This is quite awesome. If you wouldn't mind tracking down the 'blank' label template issue, we should be g2g 👍

**Comment by Nicholas-Westby** [comment]
Cool, I will look into that issue with the empty label template.

Regarding the form that doesn't make sense to you. That's a weird hack just to show you a particular example. Note the line at the top of this file: https://github.com/Nicholas-Westby/Archetype/blob/d46d64c52ba216d7d7d334267f718a7083c49f6e/app/services/archetypeLabelService.js

It is:

```javascript
angular.module('umbraco.services').factory('archetypeLabelService', function (archetypeCacheService, $q, $injector) {
```

The sample code is just a function added to that file. You should never do that of course, but it seemed like you wanted an example with just promises and no dependency injection function, so you have to resort to doing weird stuff if you want to test that (part of the reason natively supporting dependency injection is useful). In order to use promises, you need to inject a service that returns a promise, and this hack was a way to get a reference to one (in this case, the `userService`).

Hopefully that clears it up? If not, I would simply ignore that example as it shouldn't be used in practice.

**Comment by Nicholas-Westby** [comment]
FYI, the exception/blank label issue was pretty straightforward (needed to convert strings to promises that return strings). Fixed now.

**Comment by kgiszewski** [comment]
Super, will have a peek either this afternoon or first thing in the morning tomorrow.

**Comment by kgiszewski** [comment]
I'm thinking of a release in the next week or two.

I would like you to add some info here for label templates to be available with the release: https://github.com/kgiszewski/ArchetypeManual/blob/master/02%20-%20Configuration.md#label-template

Great work sir.

**Comment by Nicholas-Westby** [comment]
Will do. I'll probably get to that over the weekend.

**Comment by kgiszewski** [comment]
👍 Merged sir, thanks so much.

**Comment by Nicholas-Westby** [comment]
FYI, I plan to improve this, but here's a quick peek into the documentation I'm writing: https://github.com/Nicholas-Westby/ArchetypeManual/commit/c8f07b0c07d28b4d9dfe2aafe3392f5688cc9e07

**Comment by Nicholas-Westby** [comment]
Documentation pull request here: https://github.com/kgiszewski/ArchetypeManual/pull/6

**Pull request merged**
